#!/bin/bash

thepath=$PWD

#Script designed to translate slha to param_card
#
#Parameters to be taken from the slha that are needed for the param_card:
# BLOCK HMIX, BLOCK MASS, BLOCK MSD2, BLOCK DSQMIX, BLOCK USQMIX, BLOCK MSE2, BLOCK MSL2, BLOCK MSQ2, BLOCK MSU2, BLOCK NMIX, BLOCK SELMIX, BLOCK SNUMIX, BLOCK TD, BLOCK TE, BLOCK TU, BLOCK UMIX, BLOCK VMIX, BLOCK MSOFT, DECAY WIDTHS
#

###
## Header of the param_card
##

echo "######################################################################"
echo "## PARAM_CARD  GENERATED BY SCRIPT_SLHA_PARAM_CARD                ####"
echo "######################################################################"

##
## IMPORTANT AND SM BLOCKS: alpha, alpha_em, alpha_s, U_PMNS, V_CKM, Yukawas
##

echo "###################################"
echo "## INFORMATION FOR SMINPUTS        "
echo "###################################"
echo "BLOCK SMINPUTS #                   "
echo "      1 1.279340e+02 # aewm1       "
echo "      3 1.180000e-01 # as          "

echo "###################################"
echo "## INFORMATION FOR UPMNS           "
echo "###################################"
echo "BLOCK UPMNS #                      "
echo "      1 1 1.000000e+00 # rmns1x1   "
echo "      2 2 1.000000e+00 # rmns2x2   "
echo "      3 3 1.000000e+00 # rmns3x3   "
                                       
echo "###################################"
echo "## INFORMATION FOR VCKM            " 
echo "###################################"
echo "BLOCK VCKM #                       "
echo "      1 1 1.000000e+00 # rckm1x1   "
echo "      2 2 1.000000e+00 # rckm2x2   "
echo "      3 3 1.000000e+00 # rckm3x3   "
                                        
echo "###################################"
echo "## INFORMATION FOR YD              "
echo "###################################"
echo "BLOCK YD #                         "
echo "      3 3 1.388402e-01 # ryd3x3    "
echo "###################################"
echo "## INFORMATION FOR YE              "
echo "###################################"
echo "BLOCK YE #                         "
echo "      3 3 1.008908e-01 # rye3x3    "
echo "###################################"
echo "## INFORMATION FOR YU              "
echo "###################################"
echo "BLOCK YU #                         "
echo "      3 3 8.928445e-01 # ryu3x3    "

##
## BLOCK HMIX
##
###################################
## INFORMATION FOR FRALPHA
###################################
#BLOCK FRALPHA # 
#      1 -1.138252e-01 # alp

###################################
## INFORMATION FOR HMIX
###################################
#BLOCK HMIX # 
